import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./_layoutComponents/header/Header";
import { AllDataProvider } from "./_context/context";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AllDataProvider>
      <Header></Header>
        
        {children}
        </AllDataProvider>
        </body>
    </html>
  );
}
